# Generated by Django 2.2 on 2020-07-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('desctitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description1', models.CharField(blank=True, max_length=200, null=True)),
                ('description2', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
