# Generated by Django 2.2 on 2020-07-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_galary_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galary',
            old_name='images',
            new_name='thumbnail',
        ),
    ]
