# Generated by Django 2.2 on 2020-07-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200712_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
